[nfs]
172.31.16.193 ansible_ssh_user='ec2-user'

[webservers]
172.31.31.133 ansible_ssh_user='ec2-user'
172.31.27.75 ansible_ssh_user='ec2-user'

[db]
172.31.45.212 ansible_ssh_user='ubuntu' 

[lb]
172.31.3.60 ansible_ssh_user='ubuntu'