pipeline{
	agent any
	environment{
		ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
	}	
	

	stages{
		stage('Clean Up'){
			steps{
				cleanWs()
			}

	    }

	    stage('SCM Checkout'){
			steps{
				git branch: 'main', url: 'https://github.com/realayo/ansible-config-mgt'
			}

	    }   

	    stage('Execute Ansible'){
		steps{
			ansiblePlaybook credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'dev.yml', playbook: 'playbooks/site.yml'
		    }

	    }
	
    }
}