pipeline{
	agent any

	parameters {
		string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
	}
	environment{
		ANSIBLE_CONFIG="${WORKSPACE}/deploy/.ansible.cfg"
	}	
	

	stages{
		stage('Clean Up'){
			steps{
				cleanWs()
			}

	    }
		stage ('Scan and Build Jar File') {
			steps {
            	 withSonarQubeEnv(credentialsId: 'sonar', installationName: 'SonaQubeScanner') { 
      				sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar'
            	}
			}
		}		

	    stage('SCM Checkout'){
			steps{
				git branch: 'main', url: 'https://github.com/realayo/ansible-config-mgt'
			}

	    }   

	    stage('Execute Ansible'){
		    steps{
			    ansiblePlaybook credentialsId: 'private-key', installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
		    }

	    }
        // stage('Execute db '){
        //     steps{
        //         ansiblePlaybook credentialsId: 'private-pem', disableHostKeyChecking: true, installation: 'ansible', inventory: '${inventory}', limit: 'db', playbook: 'playbooks/site.yml'
        //     }
        // }
        // stage('Execute Ansible-Redhat'){
		//     steps{
		// 	    ansiblePlaybook credentialsId: 'private-key1', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev.yml', playbook: 'playbooks/site.yml'
		//     }

	    // }
	
    }
}