---
- hosts: all
  name: Include dynamic variables 
  tasks:
    - include: ../dynamic-assignments/env-vars.yml
- import_playbook: ../static-assignments/common.yml 
  tags:
    - always

# - hosts: webservers
# - name: Webserver assignment
#  import_playbook: ../static-assignments/webservers.yml

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml

- hosts: database
- name: import database file
  import_playbook: ../static-assignments/db.yml
  tags:
    - always

- name: Loadbalancers assignment
  hosts: lb
- import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 
